### ISSUE TITLE
train.py : RuntimeError: invalid argument 1:

### ISSUE THREAD

**Issue by ZuxianShi** [zlkanata/DeepGlobe-Road-Extraction-Challenge#2]
当我运行trian.py的时候出现这个问题，请问北邮大神遇到过吗？需要如何解决？
Traceback (most recent call last):
  File "ttest.py", line 71, in <module>
    data_loader_iter = iter(data_loader)
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 180, in __init__
    self._put_indices()
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 219, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /opt/conda/conda-bld/pytorch_1512954043090/work/torch/lib/TH/generic/THTensorMath.c:2184

**Comment by zlkanata** [comment]
应该是数据的问题，建议检查一下 "dataset/train/" 这个文件夹下的数据，如果你把deepglobe的训练数据解压在这里，应该直接就能运行起来。

**Comment by ZuxianShi** [comment]
好的，谢谢！
1、我先尝试了使用deepglobe的数据进行训练，成功了。
如果用Python3会遇到了这个问题：
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    for img, mask in data_loader_iter:
  File "/home/szx/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/home/szx/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/Software/anaconda3/envs/python-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/files/DeepGlobe-Road-original/data.py", line 125, in __getitem__
    id = self.ids[index]
TypeError: 'map' object is not subscriptable
**解决办法**在data.py中将trainlist转为list，见下面第三行
class ImageFolder(data.Dataset):
    def __init__(self, trainlist, root):
        self.ids = list(trainlist)
        self.loader = default_loader
        self.root = root
2、我会继续尝试我自己的数据，等有结果了来回复。

**Comment by ZuxianShi** [comment]
我的数据中标签图片的位深度为8，deepglobe的是24，这会不会是导致错误的原因？

**Comment by zlkanata** [comment]
如果是用的自己的数据，命名格式很可能和deepglobe的不一样。
从你最开始报的那个错来看，应该是dataloader没有读取到数据列表，也就是train.py的21、22行的imagelist和trainlist都为空，建议你打印len(imagelist)和len(trainlist)，应该都是0。
解决方法：建议修改train.py的21、22行，以及data.py的92、93行。
https://github.com/zlkanata/DeepGlobe-Road-Extraction-Challenge/blob/d274cdcb34eb93798f8ec17c7f5a200e70a2b969/train.py#L21
https://github.com/zlkanata/DeepGlobe-Road-Extraction-Challenge/blob/d274cdcb34eb93798f8ec17c7f5a200e70a2b969/data.py#L92

**Comment by zlkanata** [comment]
不客气哈~
因为deepglobe给的标签中，背景是0，道路是255，所以读取标签后，除以了255做”归一化“。
https://github.com/zlkanata/DeepGlobe-Road-Extraction-Challenge/blob/d274cdcb34eb93798f8ec17c7f5a200e70a2b969/data.py#L111
祝有好的结果！

**Comment by zlkanata** [comment]
官方没有给验证集的标签，需要将验证集的预测标签提交到官网，官方会给一个分数。

**Comment by ZuxianShi** [comment]
明白，感谢您的回复！

**Comment by ZuxianShi** [comment]
![image](https://user-images.githubusercontent.com/13671645/47056569-9448fb80-d1ef-11e8-90be-683cbdf38b16.png)
![image](https://user-images.githubusercontent.com/13671645/47056609-cbb7a800-d1ef-11e8-8dde-c3470fa18088.png)

请问你知道为什么有的地方检测不到吗？
比如上面这种情况，大路检测到了，跨越大路由上延伸到下面的路检测到了一半。
问题1是：小路左侧还有一条路，完全检测不到，感觉不合理啊？
问题2是：检测到一半的这条路大佬能不能指点一下如何优化啊？
感谢大佬回复

**Comment by zlkanata** [comment]
关于你的问题一：这条道路完全检测不出来，就说明网络以比较高的置信度判断这不是要检测出来的道路，需要查看一下数据集中类似区域是否被标注为道路了。
关于你的问题二：检测到一半其实也是置信度不够高（例如在0.4~0.6之间），但是这里暴力二值化了，道路看起来就像是断了一样。可以对概率图使用crf之类的后处理来平滑整体的置信度，这一步需要小心处理；也可以对二值化后的图使用图算法做处理（参见https://github.com/snakers4/spacenet-three的后处理部分）。

**Comment by ZuxianShi** [comment]
非常感谢！

**Comment by l53ma** [comment]
Hello, I have same question when running Python3 train.py, here is the error:

Traceback (most recent call last):
  File "train.py", line 39, in <module>
    num_workers=4)
  File "/home/ev1-ws4/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/ev1-ws4/anaconda3/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

I output the length of "imagelist" and "trainlist", which is 6226 and 0, respectively.

imagelist = filter(lambda x: x.find('sat')!=-1, os.listdir(ROOT))    #length: 6226
trainlist = map(lambda x: x[:-8], imagelist)                                  #length: 0
x = list(imagelist)
y = list(trainlist)
print(len(x), len(y))

Any ideas how to solve this problem? Many thanks.
