### ISSUE TITLE
运行train.py时出现bug，load训练数据是否有误

### ISSUE THREAD

**Issue by angleyun** [zlkanata/DeepGlobe-Road-Extraction-Challenge#24]
错误出现在train.py中低34行左右函数dataloader中data_loader = torch.utils.data.DataLoader(
    dataset,
    batch_size=batchsize,
    shuffle=True,
    num_workers=4,
    )

ValueError: num_samples should be a positive integer value, but got num_samples=0
我的运行环境为：python3.6 pytorch1.3.1
打扰您了，期待您的回复，祝您在新的一年心想事成，平安喜乐~~

**Comment by angleyun** [comment]
Traceback (most recent call last):
  File "E:/deep_learning/road_extraction/pytorch/project_research/DeepGlobe-Road-Extraction-Challenge-master/train.py", line 38, in <module>
    num_workers=4,
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
