### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512946747676/work/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by sanersbug** [zlkanata/DeepGlobe-Road-Extraction-Challenge#4]
when i run python train.py using python virtual environment it shows the error. how to solve the error,anyone solved it? thanks a lot . Another, i have tried to use small batch size,but is doesn't work. 

<torch.utils.data.dataloader.DataLoader object at 0x7f3868b7d790>
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512946747676/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    train_loss = solver.optimize()
  File "/mnt/saners-extend/DeepGlobe-Road-Extraction-Challenge/framework.py", line 62, in optimize
    pred = self.net.forward(self.img)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/saners-extend/DeepGlobe-Road-Extraction-Challenge/networks/dinknet.py", line 176, in forward
    e3 = self.encoder3(e2)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torchvision-0.1.9-py2.7.egg/torchvision/models/resnet.py", line 41, in forward
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/anaconda3/envs/road_extract/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512946747676/work/torch/lib/THC/generic/THCStorage.cu:58

**Comment by ZuxianShi** [comment]
I think it's because your memory is too small.

**Comment by ZuxianShi** [comment]
Speaking of image size: Does fixed image size have an impact on network performance? Does the fixed image length and width affect the performance of the network?When I use the 1024*1024 .shp file to diced the .tif file, there are often some dicing that are not 1024*1024. If it is not fixed, how can I modify the code?

**Comment by zlkanata** [comment]
The network can receive any input size, but due to the pooling layers and transposed-conv layers, the forward pass should have additional padding options. For computational convenience, better pad the input size to multiple of 32.

**Comment by ZuxianShi** [comment]
ok,thank you very much

**Comment by justinner** [comment]
Hello,does the code run on cpu?can I test on cpu?Thank you very much.

**Comment by SkyScraperTwc** [comment]
> Hello,does the code run on cpu?can I test on cpu?Thank you very much.

yes，you can run the code on cpu, I have tried, but It is very slow
