### ISSUE TITLE
When I run the "test.py", to about 58, there will be occur the error "ValueError: Axes=(0, 1) out of range for array of ndim=0."

### ISSUE THREAD

**Issue by GusRoth** [zlkanata/DeepGlobe-Road-Extraction-Challenge#7]
Traceback (most recent call last):
  File "test.py", line 149, in <module>
    mask = solver.test_one_img_from_path(source+name)
  File "test.py", line 32, in test_one_img_from_path
    return self.test_one_img_from_path_2(path)
  File "test.py", line 94, in test_one_img_from_path_2
    img90 = np.array(np.rot90(img))
  File "/home/yangzihao/.conda/envs/py27/lib/python2.7/site-packages/numpy/lib/function_base.py", line 121, in rot90
    .format(axes, m.ndim))
ValueError: Axes=(0, 1) out of range for array of ndim=0.

I don't konw how to solve this, please help me orz

**Comment by zlkanata** [comment]
This error means your image is not of the right shape, please check your image shape (print image.shape).
This problem is probably caused by (image == None),  so please check you have load the image correctly.

**Comment by SkyScraperTwc** [comment]
> This error means your image is not of the right shape, please check your image shape (print image.shape).
> This problem is probably caused by (image == None), so please check you have load the image correctly.

I have meat this problem, you can add  (image == None) to solve it

**Comment by KZhub3** [comment]
> > This error means your image is not of the right shape, please check your image shape (print image.shape).
> > This problem is probably caused by (image == None), so please check you have load the image correctly.
> 
> I have meat this problem, you can add (image == None) to solve it

Excuse me, where to add?
